runtime: python
env: flex
entrypoint: gunicorn -b :$PORT greaterdemand.wsgi

beta_settings:
    cloud_sql_instances: gcp-coursera-192004:us-central1:greaterdemand-postgres

runtime_config:
  python_version: 3
