# Generated by Django 2.0.1 on 2018-01-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20180122_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocuments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
